.nh
.TH "GH-ALIAS-LIST" "1" "Sep 2024" "GitHub CLI 2.57.0" "GitHub CLI manual"

.SH NAME
.PP
gh-alias-list - List your aliases


.SH SYNOPSIS
.PP
\fBgh alias list [flags]\fR


.SH DESCRIPTION
.PP
This command prints out all of the aliases gh is configured to use.


.SH ALIASES
.PP
gh alias ls


.SH EXIT CODES
.PP
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
.PP
\fBgh-alias(1)\fR
