.nh
.TH "GH-EXTENSION-LIST" "1" "Sep 2024" "GitHub CLI 2.57.0" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-list - List installed extension commands


.SH SYNOPSIS
.PP
\fBgh extension list [flags]\fR


.SH ALIASES
.PP
gh ext ls, gh extension ls, gh extensions ls


.SH EXIT CODES
.PP
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
.PP
\fBgh-extension(1)\fR
