.nh
.TH "GH-GIST-RENAME" "1" "Sep 2024" "GitHub CLI 2.57.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-rename - Rename a file in a gist


.SH SYNOPSIS
.PP
\fBgh gist rename {<id> | <url>} <oldFilename> <newFilename> [flags]\fR


.SH DESCRIPTION
.PP
Rename a file in the given gist ID / URL.


.SH EXIT CODES
.PP
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
.PP
\fBgh-gist(1)\fR
