.nh
.TH "GH-SSH-KEY-LIST" "1" "Sep 2024" "GitHub CLI 2.57.0" "GitHub CLI manual"

.SH NAME
.PP
gh-ssh-key-list - Lists SSH keys in your GitHub account


.SH SYNOPSIS
.PP
\fBgh ssh-key list [flags]\fR


.SH ALIASES
.PP
gh ssh-key ls


.SH EXIT CODES
.PP
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
.PP
\fBgh-ssh-key(1)\fR
